Task/48779 apply mvp
awesome-academy/CooktailDB pull request #2
Opened 2022-05-05 09:20 UTC by hungnd-3027

2022-05-05 09:54 UTC, daolq-2712 requested changes
Pls check my comments!

2022-05-05 09:54 UTC, daolq-2712 commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
@hungnd-3027 
project 1 mình không được dùng thư viện

code chay request api = ``HttpURLConnection``

2022-05-06 02:37 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/api/DrinkService.kt
> +    @GET("filter.php")
thêm 1 dòng trống ở giữa tên class và method hoặc field

2022-05-06 02:38 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/api/RetrofitClient.kt
> +    companion object{
tương tự

2022-05-06 02:40 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/base/BaseActivity.kt
> +    lateinit var binding: B
Khai báo binding giống  BaseFragment , tránh việc cho các accession modify biến này

2022-05-06 02:41 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/base/BaseFragment.kt
> +    val binding get() = _binding!!
ko assert non null

2022-05-06 02:42 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/model/Category.kt
> +}
Dùng data class

2022-05-06 02:42 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/model/CategoryRespond.kt
> +}
Tương tự

2022-05-06 02:43 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/model/CategoryRespond.kt
> +}
```suggestion
class CategoryRespond {
    val drinks: List<Category>  = listOf()
}
```

2022-05-06 02:44 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/model/Drink.kt
> +    var strGlass: String? = null
KO cần thiết check null tất cả các field thế này , ông gán cho nó 1 cái constant mỗi field là được

2022-05-06 07:17 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/base/BaseActivity.kt
> +    private var binding: B? = null
để private thì làm sao các children của nó dùng cái binding này đc 🧛

2022-05-06 07:19 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/base/BaseActivity.kt
> +    private var binding: B? = null
```suggestion
    private var _binding: B? = null
    val binding get() = _binding
```

các accession chỉ được phép truy cập binding chứ ko đc modify , nên sẽ viết thế này
BaseFragment tương tự nha

2022-05-06 07:19 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/base/BaseFragment.kt
> +    private val binding get() = _binding
Tương tự bên trên

2022-05-06 07:21 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/source/api/ApiURL.kt
> +        .appendPath(ApiConstants.PATH)
3 cái này sử dụng nhiều thì ông viết ra. 1 string riêng để dùng chung nhé

2022-05-06 07:51 UTC, vietnh-1109 approved these changes

2022-05-06 07:51 UTC, merged