Refs [TASK][48825] Display cocktail by selected category
awesome-academy/CooktailDB pull request #5
Opened 2022-05-11 06:32 UTC by hungnd-3027

## Related Tickets
- [#Task 48825: Display cocktails by selected category](https://edu-redmine.sun-asterisk.vn/issues/48825)
## WHAT
- Display cocktails by selected category
## Evidence (Screenshot or Video)
![Screenshot from 2022-05-11 13-31-39](https://user-images.githubusercontent.com/102728142/167783485-419c2713-88e1-4db9-a78f-1db157a52070.png)

## Review Checklist

Category | View Point | Description | Self review | Reviewer2 (name)
--- | --- | --- | --- | ---
Conventions | Sun* coding conventions | https://sal.vn/WtYPAy |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Kotlin coding conventions | https://kotlinlang.org/docs/coding-conventions.html |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Redmine | Sun* Redmine working process  | https://sal.vn/piPoQn |<li>- [ ] yes</li>|<li>- [ ] yes</li>  

## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2022-05-11 08:12 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/data/repository/DrinkRepository.kt
> -        iDrinkDataSource.getDrinks(category, callback)
cách ra 1 dòng

2022-05-11 08:12 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
> +    private lateinit var categoryAdapter: DrinkViewPagerAdapter
dùng lazy khởi tạo luôn

2022-05-11 08:13 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
>  //        TODO("Not yet implemented")
failed thì pop dialog lên hoặc toast nhé

2022-05-11 08:14 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkAdapter.kt
> +    fun setData(drinkList: MutableList<Drink>) {
```suggestion
    fun setData(drinkList: List<Drink>) {
```

2022-05-11 08:15 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkAdapter.kt
> +        fun bind(drink: Drink) {
tương tự cách ra 1 dòng

2022-05-11 08:17 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkViewPagerAdapter.kt
> +    fun setDrinkData(listDrink: MutableList<Drink>) {
data truyền vào để ImmutableList nhé , cái nào cần modify mới để Mutable

2022-05-11 08:24 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkViewPagerAdapter.kt
> +                    GridLayoutManager(context, 2)
set trong xml cho gọn

2022-05-11 08:27 UTC, vietnh-1109 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/presenter/HomeFragmentContract.kt
> +        fun getDrinkSuccess(drinks: List<Drink>)
đổi lại tên nhé

2022-05-11 08:29 UTC, vietnh-1109 commented on app/src/main/res/layout/item_drink.xml
> +
remove

2022-05-11 08:43 UTC, namnh-3013 commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
sao tên là fragment mà lại dùng activity thế ông

2022-05-11 08:43 UTC, namnh-3013 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
> +                }
tạo intent ở compaion object trong SearchActivity tương tự như tạo instance nhé ông

2022-05-11 08:43 UTC, namnh-3013 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkAdapter.kt
> +    }
```suggestion
    override fun getItemCount() = drinkList.size

```

2022-05-11 08:43 UTC, namnh-3013 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/adapter/DrinkAdapter.kt
> +                    drink.idDrink?.let { it1 -> listener?.onItemClick(it1) }
```suggestion
                    drink.idDrink?.let { idDrink -> listener?.onItemClick(idDrink }
```

2022-05-11 08:44 UTC, namnh-3013 commented
theo ý kiến cá nhân t thấy cái thanh search màu ngà ngà vàng nhìn hơi xấu, nên đổi(ví dụ trắng, xám,..)

2022-05-11 09:13 UTC, hungnd-3027 commented
oke ông, cái nút bên dưới là lấy ngẫu nhiên một cocktail, t để nhầm string

2022-05-11 09:38 UTC, namnh-3013 commented on app/src/main/java/com/example/cooktaildb/data/source/remote/RemoteDrinkDataSource.kt
> +    override fun getDrinks(param: String, callback: OnRequestCallback<List<Drink>>) {
sao chỗ này lại đổi thành param thế ông ?

2022-05-11 09:47 UTC, hungnd-3027 commented on app/src/main/java/com/example/cooktaildb/data/source/remote/RemoteDrinkDataSource.kt
> +    override fun getDrinks(param: String, callback: OnRequestCallback<List<Drink>>) {
cái này lúc đầu t nghĩ là dùng chung với api search (dùng name drink) được nên đổi thành param mà sau phải tạo cái mới nhưng chưa sửa lại

2022-05-12 02:49 UTC, daolq-2712 requested changes
Pls check my comments!

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/AndroidManifest.xml
> +            android:name=".ui.detail.DetailDrinkActivity"
```suggestion
            android:name=".ui.detail.DetailDrinkActivity"
            android:screenOrientation="portrait"
```

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/AndroidManifest.xml
> +            android:name=".ui.search.SearchActivity"
like above

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/data/repository/DrinkRepository.kt
> +): IDrinkDataSource, ISearchDrinkDataSource{
```suggestion
): IDrinkDataSource, ISearchDrinkDataSource {
```

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/MainActivity.kt
> +    NavigationBarView.OnItemSelectedListener {
```suggestion

    NavigationBarView.OnItemSelectedListener {
```
thêm 1 blank line ở ngay trên hàm

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/SplashScreenActivity.kt
> +        MainActivity.getIntent(this).also {
Không có delay vài giây à @hungnd-3027 

Như này thì là mới hiển thị màn lên chưa kịp load là vào main luôn rồi ?

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/detail/DetailDrinkActivity.kt
> +        fun getIntent(startFragment: Context) = Intent(startFragment, DetailDrinkActivity::class.java)
```suggestion
        fun getIntent(startActivity: Context) = Intent(startFragment, DetailDrinkActivity::class.java)
```
Cơ mà sao lại define thêm hàm này ấy @hungnd-3027 nhỉ?
Mình chỉ nên define khi pass thêm data kèm theo ``Intent``

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
> +    View.OnClickListener{
```suggestion
    View.OnClickListener {
```

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
> +//        categoryAdapter = DrinkViewPagerAdapter(view.context)
remove comment code!

2022-05-12 02:49 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/home_fragment/HomeFragment.kt
> +    private fun getDrinkBySelectedTab(strCategory: String?) {
sort method trong 1 class activity/ fragment nên như này em!

1. override method (from parent class mình kế thừa) - trong case này là fragment lifecycle method (onCreatedView, onStart, onStop,....)
2. public method
3. protected/ default/ internal method
4. override method (from interface implement)
5. private method
6. compaction object/ inner class

2022-05-12 03:03 UTC, hungnd-3027 commented on app/src/main/java/com/example/cooktaildb/ui/SplashScreenActivity.kt
> +        MainActivity.getIntent(this).also {
@daolq-2712  e thấy splash để tránh white page lúc ban đầu với để init data nếu cần nên e ko thêm delay vào ạ

2022-05-12 03:09 UTC, hungnd-3027 commented on app/src/main/java/com/example/cooktaildb/ui/detail/DetailDrinkActivity.kt
> +        fun getIntent(startFragment: Context) = Intent(startFragment, DetailDrinkActivity::class.java)
@daolq-2712 Giờ e sửa lại đoạn này ạ

2022-05-12 03:18 UTC, daolq-2712 commented on app/src/main/java/com/example/cooktaildb/ui/detail/DetailDrinkActivity.kt
> +        fun getIntent(startFragment: Context) = Intent(startFragment, DetailDrinkActivity::class.java)
@hungnd-3027 
Cơ mà anh thấy giữ lại cũng hay, mình dễ inspect được Class này được gọi từ những nơi nào!

Em cứ keep lại nhé!

2022-05-12 03:35 UTC, vietnh-1109 approved these changes

2022-05-12 03:43 UTC, merged